server:
  port: 5004
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    filters: sta
    maxActive: 20
    initialSite: 1
    maxWait: 60000
    minIdle: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: org.fiberhome.deviceinterface.bean
  configuration:
    map-underscore-to-camel-case: true
